### PR TITLE
feat: add command to scaffold extractor

### PR DESCRIPTION
**Pull request by scortier**
#### Command : `meteor rungen --type <type_of_extractor> --extractor <name_of_extractor>`

### CODE REVIEW

**Comment by ravisuhag** [comment]
Command interface could be more intuitive.
`$ meteor generate extractor --type=topic --name="postgres"`

**Comment by scortier** [comment]
> Command interface could be more intuitive.
> `$ meteor generate extractor --type=topic --name="postgres"` or
> `$ meteor new extractor --type=topic --name="postgres"`

Sure ,will update it

**Comment by ishanarya0** [comment]
Right, this would be better. We'll modify it.

**Comment by ravisuhag** [comment]
Also, this command would require to have a template module that will have code generation in place to generate sample code for an extractor.

**Review by ravisuhag — CHANGES_REQUESTED** [review]
Add template code generation and update comamnd

**Comment by StewartJingga** [comment]
> Command interface could be more intuitive.
> $ meteor generate extractor --type=topic --name="postgres" or
> $ meteor new extractor --type=topic --name="postgres"

`$meteor generate extractor --type=topic --name=postgres` looks good

**Review by StewartJingga — CHANGES_REQUESTED** [review]
Move generation logic to its own package.

The generation logic should be its own package, `cmd` package should only focus on gathering inputs and building dependencies.

**Comment by ishanarya0** [comment]
Added template module and file generation

WIP: Writing template content to generated files

**Pull request merged**
